version: '3.8'

services:
  stock-tracker-agent:
    build: .
    ports:
      - "8000:8000"
    environment:
      - OPENAI_API_KEY=sk-proj-12345
      - TELEGRAM_BOT_TOKEN=your_telegram_bot_token
      - TELEGRAM_CHAT_ID=your_telegram_chat_id
      - TELEGRAM_WEBHOOK_SECRET=your_webhook_secret
    env_file:
      - .env
    volumes:
      - ./logs:/app/logs
    restart: unless-stopped